name: Publish

on:
  workflow_dispatch:
    inputs:
      submit:
        description: 'Submit for review'
        required: true
        type: choice
        default: 'false'
        options:
          - true
          - false

jobs:
  publish:
    name: Publish extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compress
        run: |
          zip -r neutilities.zip . -x ".git**" -x ".vscode**" -x ".prettier*" -x "*.md" -x "LICENSE" -x "jsconfig.json"
          du -s --block-size=k neutilities.zip

      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: neutilities.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: ${{ inputs.submit }}
